### ISSUE TITLE
Data removal request for U03JT5GPT

### ISSUE THREAD

**Issue by chrisspruck** [zacstewart/tech404logs#51]
Please process the following data removal request. Thank you!

My Slack user id is U03JT5GPT: 
my Slack username is: Chris Spruck

Check all that apply with [x]:

- [x] Ignore me going forward (all future messages from me will appear as "[redacted]")
- [x] Blank out my profile and redact all historic messages from me (all past messages from me will appear as "[redacted]")
- [ ] Only redact certain historical messages from me (please provide a time range or other search criteria)

**Comment by zacstewart** [comment]
I finished up the historic message redactor task and ran it for your account. Your profile information has been blanked out and all 28 messages redacted. You can verify results by searching your user id [here](http://www.tech404logs.com/search?q=U03JT5GPT).

Note that this does not alter chat logs from any other users who may have said your name, however, in cases where people used Slack's @mention to mention you, it will now appear as `@[deleted]`, because the chat log actually stores your user id and not the username, and I replace it with current username at page render time.

If this satisfies your request, please close the ticket. If not, please let me know what else I can do.

```
Please enter the user's ID (It looks like U03H0B61B)
> U03JT5GPT
A, [2022-04-02T10:24:47.713594 #4]   ANY -- : 2022-04-02 10:24:47 +0000 severity=INFO, (0.002948s) BEGIN
A, [2022-04-02T10:24:47.716024 #4]   ANY -- : 2022-04-02 10:24:47 +0000 severity=INFO, (0.002063s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
A, [2022-04-02T10:24:47.719750 #4]   ANY -- : 2022-04-02 10:24:47 +0000 severity=INFO, (0.003368s) SELECT * FROM "users" WHERE ("id" = 'U03JT5GPT') LIMIT 1
{:id=>"U03JT5GPT",
 :name=>"chrisspruck",
 :real_name=>"Chris Spruck",
 :image=>
  "https://secure.gravatar.com/avatar/69c21b27d9fc76e1ce4a1eaa01ebab7e.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0023-48.png",
 :opted_out=>true}
A, [2022-04-02T10:24:47.881580 #4]   ANY -- : 2022-04-02 10:24:47 +0000 severity=INFO, (0.158870s) SELECT count(*) AS "count" FROM "messages" WHERE ("user_id" = 'U03JT5GPT') LIMIT 1
28 messages
Are you sure you want to redact this user? [Y/n] y
A, [2022-04-02T10:24:56.823904 #4]   ANY -- : 2022-04-02 10:24:56 +0000 severity=INFO, (0.001422s) UPDATE "users" SET "name" = '[deleted]', "real_name" = '[deleted]', "image" = '/deleted-user.png' WHERE ("id" = 'U03JT5GPT')
A, [2022-04-02T10:24:56.908675 #4]   ANY -- : 2022-04-02 10:24:56 +0000 severity=INFO, (0.084356s) UPDATE "messages" SET "text" = '[redacted]' WHERE ("user_id" = 'U03JT5GPT')
A, [2022-04-02T10:24:56.913837 #4]   ANY -- : 2022-04-02 10:24:56 +0000 severity=INFO, (0.004825s) COMMIT
```
